name: EssentialsPro
version: 1.0
main: de.marvnet.minecraft.essentialspro.main.EssentialsPro
commands:
  gamemode:
    description: Change the gamemode.
    aliases: ["gm", "gmode", "gamem"]
  fly:
    description: Toggle fly mode.
    aliases: ["toggleflymode", "flymode", "fmode", "flym", "modefly", "mfly" ,"modef"]
  broadcast:
    description: Broadcast a message on the server
    aliases: ["bc", "bcast", "broadc", "castb", "castbroad", "cbroad"]
  warp:
    description: Warp to a specific location
    aliases: ["tploc", "teleportloc", "teleportl", "tpl"]
  setwarp:
    description: Set warp location
    aliases: ["swarp", "setw", "warpset", "warps", "wset"]